### ISSUE TITLE
missing italian translation

### ISSUE THREAD

**Issue by tassoman** [shrimpia/misskey-tools#80]
https://crowdin.com/project/misskey-tools/it
onegai

**Comment by EbiseLutica** [comment]
@tassoman 

Thank you very much for your translation!

Crowdinのアカウントが制限されて、翻訳を反映できなくなってしまいました。
現在、原因を調査中です。問題が解決してから、翻訳を取り入れます。

Unfortunately, my Crowdin account has been restricted and I can no longer reflect translations right now.
I'm currently investigating this cause. I'll apply the translation after the issue is resolved.

**Comment by tassoman** [comment]
オッケ、グラツィエ

**Comment by EbiseLutica** [comment]
@tassoman I fixed the problem of Crowdin, and your translation will be released on the next version. Grazie!
